recursive: true
reporter: 'spec'

# Care not for waiting
# slow: 100
# timeout: 1000
# fail-zero: true
# bail: true

# Let bad code show its uggly face
check-leaks: true
trace-warnings: true
allow-uncaught: true
parallel: true
sort: true
exit: true # poor coding

ignore:
  - 'node_modules/**'
  - '.git/**'
  - 'build/**'
  - 'conf/**'
  - 'containers/**'
  - 'docs/**'
  - 'eslint/**'
  - 'ganeti/**'
  - 'gitlab/**'
  - 'grunt/**'
  - 'infra/**'
  - 'jenkins/**'
  - 'qatools/**'
  - 'robotframework/**'
  - 'rust/**'
  - 'scripts/**'
  - 'smc-os/**'
  - 'static/**'
  - 'tools/**'
  - 'trainings/**'
  - 'webui/**'
  - 'wiki/**'
watch-ignore:
  - 'node_modules/**'
  - '.git/**'
  - 'build/**'
  - 'conf/**'
  - 'containers/**'
  - 'docs/**'
  - 'eslint/**'
  - 'ganeti/**'
  - 'gitlab/**'
  - 'grunt/**'
  - 'infra/**'
  - 'jenkins/**'
  - 'qatools/**'
  - 'robotframework/**'
  - 'rust/**'
  - 'scripts/**'
  - 'smc-os/**'
  - 'static/**'
  - 'tools/**'
  - 'trainings/**'
  - 'webui/**'
  - 'wiki/**'
