recursive: true
reporter: 'spec'

# Care not for waiting
# slow: 100
# timeout: 1000
# fail-zero: true
# bail: true
# allow-uncaught: true

# Let bad code show its uggly face
check-leaks: true
parallel: true
sort: true
exit: true # poor coding
